---
- name: Create Galileo Group
  ansible.builtin.group:
    name: galileo
    state: present
    gid: "{{ galileo_gid | default(omit) }}"

- name: Create Galileo User
  ansible.builtin.user:
    name: galileo
    uid: "{{ galileo_uid | default(omit) }}"
    home: /opt/galileo
    group: galileo
    create_home: false

- name: Check if /etc/cron.allow exists
  ansible.builtin.stat:
    path: /etc/cron.allow
  register: cron_allow_file

- name: If necessary, add galileo to /etc/cron.allow
  ansible.builtin.lineinfile:
    path: /etc/cron.allow
    line: galileo
    state: present
  when: cron_allow_file.stat.exists

- name: Set the Galileo password to never expire
  ansible.builtin.user:
    name: galileo
    password_expire_max: -1
