---
- name: Galileo install for AIX
  when: ansible_system | lower == 'aix'
  block:
    - name: Prep AIX OS to install Galileo
      ansible.builtin.include_tasks:
        file: tasks/aix-prep.yml

    # - name: Change python path to /usr/bin for localhost
    #   ansible.builtin.set_fact:
    #     ansible_python_interpreter: /usr/bin/python3

    - name: Run AIX comm install playbook
      ansible.builtin.include_tasks:
        file: tasks/comm.yml

    # - name: Change python path to /opt/freeware/bin/python3
    #   ansible.builtin.set_fact:
    #     ansible_python_interpreter: /opt/freeware/bin/python3

    - name: Run AIX agent install playbook
      ansible.builtin.include_tasks:
        file: tasks/agent.yml

- name: Galileo install for Linux
  when: ansible_system | lower == 'linux'
  block:
    - name: Prep Linux OS to install Galileo
      ansible.builtin.include_tasks:
        file: tasks/linux-prep.yml

    - name: Run comm and agent install playbook
      ansible.builtin.include_tasks:
        file: tasks/repo-comm.yml
