---
- name: Configure Galileo Repository
  ansible.builtin.yum_repository:
    name: galileo
    description: Galileo Performance Explorer Agents
    enabled: true
    baseurl: "{{ galileo_repo_url }}"
    gpgkey: "{{ galileo_repo_gpgkey }}"

- name: Try to install using yum
  ansible.builtin.yum:
    name: "{{ galileo_agent_list }}"
    state: present
    use_backend: "{{ 'dnf' | default(omit) }}"
  register: installed_rpms

- name: Enable proxy Auth if user and password were provided
  ansible.builtin.set_fact:
    galileo_proxy_auth_required: "{% if galileo_proxy_user is defined and galileo_proxy_password is defined %}true{% endif %}"
  when: galileo_proxy is defined and galileo_proxy_port is defined

- name: Lay down galileo answer file
  ansible.builtin.template:
    dest: /tmp/galileo_comm_answer_file.txt
    src: galileo_comm_answer_file.txt.j2
    mode: "0644"

- name: Remove existing registration
  ansible.builtin.shell: |
    set -o pipefail
    echo y | /opt/galileo/bin/gpe-agent-comm del_service {{ galileo_service }}
  register: del_service_result
  changed_when: del_service_result.rc == 0

# Temporary workaround for RHEL 9 on ppc64le
- name: Copy file to /opt/galileo/bin
  ansible.builtin.copy:
    src: nmon
    dest: /opt/galileo/bin/nmon
    mode: "0755"
  when: ansible_distribution_major_version == '9' and ansible_architecture == 'ppc64le'

- name: Copy NMON to /opt/galileo/bin
  ansible.builtin.copy:
    src: nmon_power_64le_rhel9
    dest: /opt/galileo/bin/nmon_power_64le_rhel9
    mode: "0755"
  when: ansible_distribution_major_version == '9' or ansible_architecture == 'ppc64le'

- name: Register newly installed agent with galileo
  ansible.builtin.command:
    cmd: /opt/galileo/bin/gpe-agent-comm add_service --file /tmp/galileo_comm_answer_file.txt
  register: comm_registration
  changed_when: comm_registration.rc == 0

- name: Validate registration succeeded by attempting a send
  ansible.builtin.command:
    cmd: /opt/galileo/bin/gpe-agent-comm send {{ galileo_service }} {{ galileo_site }}
  register: comm_send
  changed_when: comm_send.rc == 0

- name: Remove answer file
  ansible.builtin.file:
    path: /tmp/galileo_comm_answer_file.txt
    state: absent
  when: comm_registration.rc == 0

# Remove repo to avoid being updated during an update all
- name: Remove repository (and clean up left-over metadata)
  ansible.builtin.yum_repository:
    name: galileo
    state: absent
