---
- name: Configure Galileo Repository
  ansible.builtin.yum_repository:
    name: galileo
    description: Galileo Performance Explorer Agents
    enabled: true
    baseurl: "{{ galileo_repo_url }}"
    gpgkey: "{{ galileo_repo_gpgkey }}"

- name: Try to install using yum
  ansible.builtin.yum:
    name: "{{ galileo_agent_list }}"
    state: present
    use_backend: "{{'dnf' | default(omit)}}"
  register: installed_rpms

- name: Enable proxy Auth if user and password were provided
  ansible.builtin.set_fact:
    galileo_proxy_auth_required: "{% if galileo_proxy_user is defined and galileo_proxy_password is defined %}true{% endif %}"
  when: galileo_proxy is defined and galileo_proxy_port is defined

- name: Lay down galileo answer file
  ansible.builtin.template:
    dest: /tmp/galileo_comm_answer_file.txt
    src: galileo_comm_answer_file.txt.j2

- name: Remove existing registration
  ansible.builtin.shell:
    cmd: echo y | /opt/galileo/bin/gpe-agent-comm del_service Galileo_Xfer_Service

- name: Register newly installed agent with galileo
  ansible.builtin.shell:
    cmd: /opt/galileo/bin/gpe-agent-comm add_service --file /tmp/galileo_comm_answer_file.txt
  register: comm_registration

- name: Validate registration succeeded by attempting a send
  ansible.builtin.shell:
    cmd: /opt/galileo/bin/gpe-agent-comm send {{ galileo_service }} {{ galileo_site }}

#- name: Remove answer file
#  ansible.builtin.file:
#    path: /tmp/galileo_comm_answer_file.txt
#    state: absent
#  when: comm_registration.rc == 0

# Remove repo to avoid being updated
- name: Remove repository (and clean up left-over metadata)
  ansible.builtin.yum_repository:
    name: galileo
    state: absent
  notify: yum-clean-metadata
